<?php
/**
 * Created by PhpStorm.
 * User: zguangjian
 * Date: 2019/7/24
 * Time: 11:28
 * Email: zguangjian@outlook.com
 */

namespace zguangjian\Extend;

use zguangjian\Config;
use zguangjian\Events\OAuthInterface;

/**
 * Class Google
 * @package zguangjian\Extend
 */
class Google extends OAuthInterface
{
    public $payload;
    /**
     * @var string
     */
    protected $GetRequestCodeURL = "https://accounts.google.com/o/oauth2/v2/auth";
    /**
     * @var string
     */
    protected $GetAccessTokenURL = "https://accounts.google.com/o/oauth2/v4/token";
    /**
     * @var string
     */
    protected $GetAccessUserInfoURL = "https://www.googleapis.com/gmail/v1/users/{userId}/labels";

    /**
     * Google constructor.
     * @param Config $config
     */
    public function __construct(Config $config)
    {

    }

    /**
     * @return mixed|void
     */
    public function getCode()
    {
        parent::getCode(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $code
     * @return mixed|void
     */
    protected function getToken(string $code)
    {
        parent::getToken($code); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $code
     * @return mixed|void
     */
    public function getUserInfo(string $code)
    {
        parent::getUserInfo($code); // TODO: Change the autogenerated stub
    }
}